# -*- coding: utf-8 -*-
"""Taller 2 logica.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1cS5nwEb_RBzr2fjESCHZb_JY5ekojeM0

#ejercicios 1, 2 y 3
"""

def bienvenida(edad):

   def pedirEdad():
       if edad >= 18:
         print("Bienvenido al programa, eres mayor de edad.")
       else:
         print("Usted no es mayor de edad, por lo tanto no puede acceder al programa, cuando cumplas 18 puedes acceder. ")
   pedirEdad()

   def generacionPerteneciente():
       if 24 < edad <= 40:
         print("Perteneces a la generacion millenial. ")
       elif 10 < edad <= 24:
         print("Perteneces a la generacion Z. ")
       elif 0 < edad <= 10:
         print("Perteneces a la generacion alfa. ")
       else:
         print("Perteneces a la generacion Boomer. ")

   generacionPerteneciente()

   def numeroRedondo():
       if edad % 10 == 0:
         print("Tu edad es un numero terminado en 0. ")
         return True
       else:
         print("Tu edad no termina en 0. ")
         return False
   numeroRedondo()

mensajeBienvenida=input("Ingresa tu nombre: ")
print(f"Bienvenido al programa, {mensajeBienvenida}")
edad=int(input("ingrese su edad: "))
bienvenida(edad)

#ejercicio 4

contactos = {"Cantera": 3214659823,
             "Quintero": 3126654891,
             "Guerrero": 3186214879,}
variableMenu= True

while variableMenu:
   print("1. Agregar un contacto")
   print("2. Buscar un contacto")
   print("3. Mostrar un contacto")
   print("4. Editar un contacto")

   opcion= input("Seleccione una de las opciones: \n")

   if opcion == "0":
       variableMenu=False
   elif opcion == "1":
       nombre=input("Ingresa el nombre del contacto: \n")
       numero=int(input("Ingrese el numero del contacto: \n"))
       contactos[nombre]= numero
       print(f"{nombre}, ha sido agregado a la lista de contactos" )
   elif opcion == "2":
       nombre=input("Ingresa el nombre del contacto: \n")
       telefono=contactos[nombre]
       print(f"el numero de {nombre} es: {telefono}. ")
   elif opcion == "3":
       nombre=input("Escoja el contacto que desea ver: ")
       print(f"El numero es: ¨{contactos[nombre]} ")
   elif opcion == "4":
       nombre=input("Ingrese el nombre del contacto qu va modificar: \n")
       numeroNuevo=int(input("Ingrese el nuevo numero: \n"))
       contactos[nombre]= numeroNuevo

#Ejercicio 5: Organizando una Fiesta

def agregarInvitado(listaInvitados, nombre):
    listaInvitados.append(nombre)

def eliminarInvitado(listaInvitados, nombre):
    if nombre in listaInvitados:
        listaInvitados.remove(nombre)
    else:
        print("El invitado no está en la lista.")

def verificarInvitado(listaInvitados, nombre):
    return nombre in listaInvitados

def editarInvitado(listaInvitados, nombreAntiguo, nombreNuevo):
    if nombreAntiguo in listaInvitados:
        index=listaInvitados.index(nombreAntiguo)
        listaInvitados[index]=nombreNuevo
    else:
        print("El invitado no está en la lista.")

# Ejemplo de uso
listaInvitados=[]
while True:
    print("1. Agregar Invitado")
    print("2. Eliminar Invitado")
    print("3. Verificar Invitado")
    print("4. Editar Invitado")
    print("5. Salir")
    opcion = int(input("Elige una opción: "))

    if opcion == 1:
        nombre=input("Ingresa el nombre del invitado: ")
        agregarInvitado(listaInvitados, nombre)
    elif opcion == 2:
        nombre=input("Ingresa el nombre del invitado que quieres eliminar: ")
        eliminarInvitado(listaInvitados, nombre)
    elif opcion == 3:
        nombre=input("Ingresa el nombre del invitado que quieres verificar: ")
        if verificarInvitado(listaInvitados, nombre):
            print(f"{nombre} está en la lista de invitados.")
        else:
            print(f"{nombre} no está en la lista de invitados.")
    elif opcion == 4:
        nombreAntiguo=input("Ingresa el nombre del invitado que quieres editar: ")
        nombreNuevo=input("Ingresa el nuevo nombre: ")
        editarInvitado(listaInvitados, nombreAntiguo, nombreNuevo)
    elif opcion == 5:
        break
    else:
        print("Opción no válida.")